require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

# rubocop

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

# rubocop-rspec

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true
